### ISSUE TITLE
Recursion troubles while building a recursive parser

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#84]
I'm trying to make some non-left recursion (for what I understand). I've tried on arithmetic stuff, then tried on this minimal work:

``` js
const {stream, F, N, C, X} = require('parser-combinator');

function A(){
    return C.char('A').then(B());
}

function B(){
    return C.char('B').or(A());
}

let parsing = A().parse(stream.ofString('AAAAAB'));
console.log(parsing);
```

And I always have this:

```
=== Building Parser ====
RangeError: Maximum call stack size exceeded
    at Object.char (C:\code\...\chars-bundle.js:58:33)
    at B (integration-npm\examples\a-recursion.js:10:14)
    at A (integration-npm\examples\a-recursion.js:6:27)
    at B (integration-npm\examples\a-recursion.js:10:27)
    at A (integration-npm\examples\a-recursion.js:6:27)
    at B (integration-npm\examples\a-recursion.js:10:27)
    at A (integration-npm\examples\a-recursion.js:6:27)
```

I think the parser construction loops forever before starting to parse.

**Comment by d-plaindoux** [comment]
This is an unfortunately expected behaviour:
- A() creates a B() which creates a A() ad-libitum

Lazy parser should be used in such case as shown in the next code sample:
``` js
const {stream, F, N, C, X} = require('parser-combinator');

function A(){
    return C.char('A').then(F.lazy(B));
}

function B(){
    return C.char('B').or(F.lazy(A));
}

let parsing = A().parse(stream.ofString('AAAAAB'));
console.log(parsing);
```

**Comment by nicolas-zozol** [comment]
Thanks +1 . I was just reading that ;)

**Comment by nicolas-zozol** [comment]
``` js
const {stream, F, N, C, X} = require('parser-combinator');

function A(){
    return C.char('A').then(B());
}

function B(){
    return C.char('B').or(F.lazy(A));
}


console.log('=== Building Parser ====');
const parser = A();
console.log('=== GETTING THERE ====');
let parsing = parser.parse(stream.ofString('AAAAAB'));
console.log(parsing);
```

Now having:

> 
> === Building Parser ====
> === GETTING THERE ====
> Accept {
>   offset: 6,
>   consumed: true,
>   value: [ 'A', 'A', 'A', 'A', 'A', 'B' ],
>   input: StringStream { source: 'AAAAAB' } }
>
